[versions]
kotlin = "2.3.20-RC" # https://github.com/jetbrains/kotlin/releases
kotlinTest = "2.3.20-Beta2"
jvmToolchain = "21"
jvmTarget = "21"
minSdk = "29"
targetSdk = "36"
compileSdk = "36"
buildToolsVersion = "36.1.0"
compileSdkPreview = "Baklava"
androidGradlePlugin = "9.0.1"
androidVersion = "4.1.1.4"
#lint = "31.4.0"
desugarJdkLibs = "2.1.5"
kotlinDatetime = "0.7.1"
kotlinPoet = "2.2.0" # https://github.com/square/kotlinpoet/releases
kotlinWrappersBom = "2026.2.15" # https://github.com/JetBrains/kotlin-wrappers/releases
jetbrainsCompose = "1.10.1" # https://github.com/JetBrains/compose-multiplatform/releases
jetbrainsCore = "1.0.1"
jetbrainsWindowCore = "1.5.1"
jetbrainsSavedState = "1.4.0"
kotlinCoroutines = "1.10.2"
kotlinSerialization = "1.10.0"
kotlinCollectionsImmutable = "0.4.0"
ksp = "2.3.4" # https://github.com/google/ksp/releases
ktor = "3.4.0" # https://github.com/ktorio/ktor/releases
kermit = "2.0.8"
room = "2.8.4"
sqlite = "2.6.2"
datastore = "1.2.0"
activityKtx = "1.12.4"
fragmentKtx = "1.8.9"
lifecycle = "2.9.6" # https://mvnrepository.com/artifact/org.jetbrains.androidx.lifecycle/lifecycle-viewmodel
lifecycleProcess = "2.10.0"
lifecycleViewmodelNavigation3 = "2.10.0-alpha08"
googlePlayServices = "4.4.4"
playServicesWearable = "19.0.0"
crashlytics = "3.0.6"
firebasePerf = "2.0.2"
firebaseBom = "34.9.0"
window = "1.5.1"
appcompat = "1.7.1"
coreKtx = "1.17.0"
coreSplashscreen = "1.2.0"
collectionKtx = "1.5.0"
annotation = "1.9.1"
paletteKtx = "1.0.0"
workRuntimeKtx = "2.11.1"
preferenceKtx = "1.2.1"
metricsPerformance = "1.0.0"
composeAdaptiveNavigation3 = "1.3.0-alpha03"
composeLintChecks = "1.4.2"
composeMaterial3 = "1.11.0-alpha01"
composeMaterialIconsExtended = "1.7.3"
composeNavigation3Ui = "1.0.0-alpha06"
metro = "0.10.4" # https://github.com/ZacSweers/metro/releases
wearCompose = "1.5.6"
accompanist = "0.37.3" # https://github.com/google/accompanist/releases
junit = "4.13.2"
junitExt = "1.3.0"
espressoCore = "3.7.0"
uiTestJunit4 = "1.10.3" # https://mvnrepository.com/artifact/androidx.compose.ui/ui-test-junit4
mockk = "1.14.9"
robolectric = "4.16.1"
roborazzi = "1.59.0"
junitPlatform = "6.0.3"
assertjCore = "3.27.7"
slf4jSimple = "2.0.17"
detekt = "2.0.0-alpha.2"
#detektFormatting = "1.23.8"
#robsRules = "1.0.2"
ksoup = "0.6.0"
coil = "3.3.0"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
room = { id = "androidx.room", version.ref = "room" }
googlePlayServices = { id = "com.google.gms.google-services", version.ref = "googlePlayServices" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
firebasePerf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
detektGradle = { id = "dev.detekt", version.ref = "detekt" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

[libraries]
composeAnimation = { group = "org.jetbrains.compose.animation", name = "animation", version.ref = "jetbrainsCompose" }
composeAnimationGraphics = { group = "org.jetbrains.compose.animation", name = "animation-graphics", version.ref = "jetbrainsCompose" }
composeComponentsAnimatedImage = { group = "org.jetbrains.compose.components", name = "components-animatedimage", version.ref = "jetbrainsCompose" }
composeComponentsResources = { group = "org.jetbrains.compose.components", name = "components-resources", version.ref = "jetbrainsCompose" }
composeComponentsSplitPane = { group = "org.jetbrains.compose.components", name = "components-splitpane", version.ref = "jetbrainsCompose" }
composeDesktop = { group = "org.jetbrains.compose.desktop", name = "desktop", version.ref = "jetbrainsCompose" }
composeFoundation = { group = "org.jetbrains.compose.foundation", name = "foundation", version.ref = "jetbrainsCompose" }
composeMaterial3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "composeMaterial3" }
composeMaterial3WindowSizeClass = { group = "org.jetbrains.compose.material3", name = "material3-window-size-class", version.ref = "composeMaterial3" }
composeMaterialIconsExtended = { group = "org.jetbrains.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIconsExtended" }
composeNavigation3Ui = { group = "org.jetbrains.androidx.navigation3", name = "navigation3-ui", version.ref = "composeNavigation3Ui" }
composeNavigation3Material3Adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "composeAdaptiveNavigation3" }
composeRuntime = { group = "org.jetbrains.compose.runtime", name = "runtime", version.ref = "jetbrainsCompose" }
composeUi = { group = "org.jetbrains.compose.ui", name = "ui", version.ref = "jetbrainsCompose" }
composeUiTooling = { group = "org.jetbrains.compose.ui", name = "ui-tooling", version.ref = "jetbrainsCompose" }
composeUiToolingPreview = { group = "org.jetbrains.compose.ui", name = "ui-tooling-preview", version.ref = "jetbrainsCompose" }
composeUiUtil = { group = "org.jetbrains.compose.ui", name = "ui-util", version.ref = "jetbrainsCompose" }
composeUiTest = { group = "org.jetbrains.compose.ui", name = "ui-test", version.ref = "jetbrainsCompose" }
kotlinCoroutinesBom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinCoroutines" }
#kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }
kotlinCoroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing" }
#kotlinCoroutinesJavaFx = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-javafx" }
kotlinCoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotlinSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinCollectionsImmutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinCollectionsImmutable" }
kotlinDatetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlinWrappersBom = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-wrappers-bom", version.ref = "kotlinWrappersBom" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }

desugarJdkLibsNio = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugarJdkLibs" }
#lintApi = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
#lintChecks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "lint" }
#lintCli = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
#lintTests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }

# used for annotation processing only
android = { group = "com.google.android", name = "android", version.ref = "androidVersion" }
metroRuntimeJvm = { group = "dev.zacsweers.metro", name = "runtime-jvm", version.ref = "metro" }

kspSymbolProcessingApi = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinPoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoetKsp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinPoet" }

firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseCrashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebaseAnalytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebasePerf = { group = "com.google.firebase", name = "firebase-perf" }

ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientAndroid = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktorClientJvm = { group = "io.ktor", name = "ktor-client-apache5", version.ref = "ktor" }
ktorClientDarwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
#ktorClientJs = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktorClientLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationKotlinJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorCoilJvm = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coilNetwork = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomPaging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
sqliteBundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastorePreferencesCore = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
datastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastoreCoreOkio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore" }
datastoreCoreOkioJvm = { group = "androidx.datastore", name = "datastore-core-okio-jvm", version.ref = "datastore" }

window = { group = "androidx.window", name = "window", version.ref = "window" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coreSplashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

collectionKtx = { group = "androidx.collection", name = "collection-ktx", version.ref = "collectionKtx" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
paletteKtx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }
workRuntimeKtx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
preferenceKtx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
metricsPerformance = { group = "androidx.metrics", name = "metrics-performance", version.ref = "metricsPerformance" }

lifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
#lifecycleViewModelSavedState = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate" }

jetbrainsLifecycleRuntimeCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
jetbrainsLifecycleViewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
jetbrainsLifecycleViewmodelCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
jetbrainsLifecycleViewmodelNavigation3 = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNavigation3" }
jetbrainsCore = { group = "org.jetbrains.androidx.core", name = "core-bundle", version.ref = "jetbrainsCore" }
jetbrainsWindowCore = { group = "org.jetbrains.androidx.window", name = "window-core", version.ref = "jetbrainsWindowCore" }
jetbrainsSavedState = { group = "org.jetbrains.androidx.savedstate", name = "savedstate", version.ref = "jetbrainsSavedState" }

composeLintChecks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "composeLintChecks" }

composeMaterialWear = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wearCompose" }
composeNavigationWear = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "wearCompose" }

accompanistAdaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }

ksoup = { group = "com.mohamedrejeb.ksoup", name = "ksoup-html", version.ref = "ksoup" }

playServicesWearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }

slf4jSimple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4jSimple" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
junitExt = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "uiTestJunit4" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazziCompose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazziJUnitRule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitPlatform" }
junitPlatformEngine = { group = "org.junit.platform", name = "junit-platform-engine", version.ref = "junitPlatform" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertjCore" }

ktlint = { group = "dev.detekt", name = "detekt-rules-ktlint-wrapper", version.ref = "detekt" }
#detektFormatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detektFormatting" }
#robsRules = { group = "dev.robch.rules", name = "robs-rules", version.ref = "robsRules" }

[bundles]
commonMain = [
    "composeAnimation",
    "composeAnimationGraphics",
    "composeComponentsResources",
    "composeFoundation",
    "composeMaterial3",
    "composeMaterial3WindowSizeClass",
    "composeMaterialIconsExtended",
    "composeRuntime",
    "composeUi",
    "composeUiToolingPreview",
    "composeUiUtil",
    "annotation",
    "coil",
    "coilNetwork",
    "datastore",
    "datastoreCoreOkio",
    "datastorePreferences",
    "datastorePreferencesCore",
    "jetbrainsCore",
    "jetbrainsLifecycleRuntimeCompose",
    "jetbrainsLifecycleViewmodel",
    "jetbrainsLifecycleViewmodelCompose",
    "jetbrainsLifecycleViewmodelNavigation3",
    "jetbrainsSavedState",
    "jetbrainsWindowCore",
    "kermit",
    "kotlinCollectionsImmutable",
    "kotlinDatetime",
    "kotlinSerializationJson",
    "ksoup",
    "ktorClientContentNegotiation",
    "ktorClientCore",
    "ktorClientLogging",
    "ktorSerializationKotlinJson",
    "composeNavigation3Ui",
    "composeNavigation3Material3Adaptive",
    "roomRuntime",
    "slf4jSimple",
    "sqliteBundled",
]
androidMain = [
    "accompanistAdaptive",
    "activityKtx",
    "appcompat",
    "collectionKtx",
    "composeUiTooling",
    "composeDesktop",
    "composeComponentsAnimatedImage",
    "composeComponentsSplitPane",
    "coreKtx",
    "coreSplashscreen",
    "firebaseAnalytics",
    "firebaseCrashlytics",
    "firebasePerf",
    "fragmentKtx",
    "kotlinCoroutinesAndroid",
    "kspSymbolProcessingApi",
    "ktorClientAndroid",
    "lifecycleProcess",
    "metricsPerformance",
    "paletteKtx",
    "preferenceKtx",
    "roomKtx",
    "roomPaging",
    "roomRuntime",
    "window",
    "workRuntimeKtx",
]
jvmMain = [
    "datastoreCoreOkioJvm",
    "kotlinCoroutinesSwing",
    "ktorClientJvm",
    "ktorCoilJvm",
]
wear = [
    "composeMaterialWear",
    "composeNavigationWear",
    "playServicesWearable",
]
iosMain = [
    "ktorClientDarwin",
]
commonTest = [
    "composeUiTest",
    "kotlinCoroutinesTest",
    "kotlinTest",
]
androidUnitTest = [
    "assertjCore",
    "espressoCore",
    "junit",
    "junitExt",
    "junitJupiter",
    "mockk",
    "robolectric",
    "roborazzi",
    "roborazziCompose",
    "roborazziJUnitRule",
    "uiTestJunit4",
]
#lintApi = [
#    "kotlinStdlib",
#    "lintApi",
#    "lintChecks",
#]
#lintTests = [
#    "junit",
#    "lintCli",
#    "lintTests"
#]
