[versions]
buildToolsVersion = "36.0.0"
jvmToolchain = "21"
jvmTarget = "21"
minSdk = "28"
targetSdk = "36"
compileSdk = "36"
compileSdkPreview = "Baklava"
android = "8.13.0"
#lint = "31.4.0"
desugarJdkLibs = "2.1.5"
kotlin = "2.2.20" # https://github.com/jetbrains/kotlin/releases
ksp = "2.2.20-2.0.3" # https://github.com/google/ksp/releases
kotlinPoet = "2.2.0" # https://github.com/square/kotlinpoet/releases
kotlinWrappersBom = "2025.9.7" # https://github.com/JetBrains/kotlin-wrappers/releases
jetbrainsCompose = "1.9.0-rc02" # https://github.com/JetBrains/compose-multiplatform/releases
jetbrainsComposeHotReload = "1.0.0-beta06" # https://mvnrepository.com/artifact/org.jetbrains.compose.hot-reload/hot-reload-gradle-plugin/
kotlinCoroutines = "1.10.2"
kotlinSerialization = "1.9.0"
kotlinCollectionsImmutable = "0.4.0"
material3WindowSizeClassMultiplatform = "0.5.0"
kotlinDatetime = "0.7.1"
ktor = "3.3.0" # https://github.com/ktorio/ktor/releases
kermit = "2.0.8"
room = "2.8.0"
sqlite = "2.6.0"
datastore = "1.1.7"
activityKtx = "1.11.0"
fragmentKtx = "1.8.9"
lifecycle = "2.9.3" # https://mvnrepository.com/artifact/org.jetbrains.androidx.lifecycle/lifecycle-viewmodel
navigationCompose = "2.9.0-rc02" # https://mvnrepository.com/artifact/org.jetbrains.androidx.navigation/navigation-compose
#navigation = "2.8.7"
googlePlayServices = "4.4.3"
playServicesWearable = "19.0.0"
crashlytics = "3.0.6"
firebasePerf = "2.0.1"
firebaseBom = "34.2.0"
window = "1.4.0"
appcompat = "1.7.1"
coreKtx = "1.17.0"
coreSplashscreen = "1.0.1"
collectionKtx = "1.5.0"
annotation = "1.9.1"
paletteKtx = "1.0.0"
workRuntimeKtx = "2.10.4"
preferenceKtx = "1.2.1"
metricsPerformance = "1.0.0-beta04"
composeLintChecks = "1.4.2"
material3 = "1.5.0-alpha04"
material3Adaptive = "1.2.0-beta02"
metro = "0.6.6" # https://github.com/ZacSweers/metro/releases
wearCompose = "1.5.1"
accompanist = "0.37.3" # https://github.com/google/accompanist/releases
junit = "4.13.2"
junitExt = "1.3.0"
espressoCore = "3.7.0"
uiTestJunit4 = "1.9.1" # https://mvnrepository.com/artifact/androidx.compose.ui/ui-test-junit4
mockk = "1.14.5"
robolectric = "4.16"
roborazzi = "1.50.0"
junitJupiter = "6.0.0-RC2"
junitPlatform = "1.13.4"
assertjCore = "3.27.4"
slf4jSimple = "2.0.17"
detekt = "1.23.8"
robsRules = "1.0.2"
ksoup = "0.6.0"
coil = "3.3.0"

[libraries]
plugin-kotlinGradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlinParcelize = { group = "org.jetbrains.kotlin.plugin.parcelize", name = "org.jetbrains.kotlin.plugin.parcelize.gradle.plugin", version.ref = "kotlin" }
plugin-kotlinSerialization = { group = "org.jetbrains.kotlin.plugin.serialization", name = "org.jetbrains.kotlin.plugin.serialization.gradle.plugin", version.ref = "kotlin" }
plugin-compose = { group = "org.jetbrains.kotlin.plugin.compose", name = "org.jetbrains.kotlin.plugin.compose.gradle.plugin", version.ref = "kotlin" }
plugin-composeCompiler = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "jetbrainsCompose" }
plugin-composeHotReload = { group = "org.jetbrains.compose.hot-reload", name = "hot-reload-gradle-plugin", version.ref = "jetbrainsComposeHotReload" }
plugin-androidApplication = { group = "com.android.application", name = "com.android.application.gradle.plugin", version.ref = "android" }
plugin-androidLibrary = { group = "com.android.library", name = "com.android.library.gradle.plugin", version.ref = "android" }
plugin-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-metro = { group = "dev.zacsweers.metro", name = "gradle-plugin", version.ref = "metro" }
plugin-room = { group = "androidx.room", name = "androidx.room.gradle.plugin", version.ref = "room" }
plugin-googlePlayServices = { group = "com.google.gms.google-services", name = "com.google.gms.google-services.gradle.plugin", version.ref = "googlePlayServices" }
plugin-crashlytics = { group = "com.google.firebase.crashlytics", name = "com.google.firebase.crashlytics.gradle.plugin", version.ref = "crashlytics" }
plugin-firebasePerf = { group = "com.google.firebase.firebase-perf", name = "com.google.firebase.firebase-perf.gradle.plugin", version.ref = "firebasePerf" }
plugin-detektGradle = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
plugin-roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi-gradle-plugin", version.ref = "roborazzi" }

# dependencies
kotlinCoroutinesBom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinCoroutines" }
#kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinCoroutinesAndroid = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android" }
kotlinCoroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing" }
#kotlinCoroutinesJavaFx = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-javafx" }
kotlinCoroutinesTest = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotlinSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }
kotlinCollectionsImmutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinCollectionsImmutable" }
kotlinDatetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlinWrappersBom = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-wrappers-bom", version.ref = "kotlinWrappersBom" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

desugarJdkLibsNio = { group = "com.android.tools", name = "desugar_jdk_libs_nio", version.ref = "desugarJdkLibs" }
#lintApi = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
#lintChecks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "lint" }
#lintCli = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
#lintTests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }

kspSymbolProcessingApi = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
kotlinPoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoetKsp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinPoet" }

firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseCrashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebaseAnalytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebasePerf = { group = "com.google.firebase", name = "firebase-perf" }

ktorClientCore = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktorClientAndroid = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktorClientJvm = { group = "io.ktor", name = "ktor-client-apache5", version.ref = "ktor" }
ktorClientDarwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
#ktorClientJs = { group = "io.ktor", name = "ktor-client-js", version.ref = "ktor" }
ktorClientLogging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationKotlinJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorCoilJvm = { group = "io.ktor", name = "ktor-client-java", version.ref = "ktor" }

coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coilNetwork = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomPaging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
sqliteBundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastorePreferencesCore = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
datastorePreferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastoreCoreOkio = { group = "androidx.datastore", name = "datastore-core-okio", version.ref = "datastore" }
datastoreCoreOkioJvm = { group = "androidx.datastore", name = "datastore-core-okio-jvm", version.ref = "datastore" }

window = { group = "androidx.window", name = "window", version.ref = "window" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coreSplashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

collectionKtx = { group = "androidx.collection", name = "collection-ktx", version.ref = "collectionKtx" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
paletteKtx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }
workRuntimeKtx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
preferenceKtx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
metricsPerformance = { group = "androidx.metrics", name = "metrics-performance", version.ref = "metricsPerformance" }

lifecycleProcess = { group = "androidx.lifecycle", name = "lifecycle-process" }
#lifecycleViewModelSavedState = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate" }

jetbrainsLifecycleRuntimeCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
jetbrainsLifecycleViewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
jetbrainsLifecycleViewmodelCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
jetbrainsNavigationCompose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
jetbrainsCore = { group = "org.jetbrains.androidx.core", name = "core-bundle", version = "1.0.1" }
jetbrainsWindowCore = { group = "org.jetbrains.androidx.window", name = "window-core", version = "1.3.1" }
jetbrainsSavedState = { group = "org.jetbrains.androidx.savedstate", name = "savedstate", version = "1.3.3" }

#navigationUiKtx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

composeLintChecks = { group = "com.slack.lint.compose", name = "compose-lint-checks", version.ref = "composeLintChecks" }

material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3WindowSizeClassMultiplatform = { group = "dev.chrisbanes.material3", name = "material3-window-size-class-multiplatform", version.ref = "material3WindowSizeClassMultiplatform" }
material3Adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3Adaptive" }
material3AdaptiveLayout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3Adaptive" }
material3AdaptiveNavigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version = "1.1.2" }
material3AdaptiveNavigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version = "1.4.0-rc01" }

composeMaterialWear = { group = "androidx.wear.compose", name = "compose-material", version.ref = "wearCompose" }
composeNavigationWear = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "wearCompose" }

accompanistAdaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }

ksoup = { group = "com.mohamedrejeb.ksoup", name = "ksoup-html", version.ref = "ksoup" }

playServicesWearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }

slf4jSimple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4jSimple" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
junitExt = { group = "androidx.test.ext", name = "junit", version.ref = "junitExt" }
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
uiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }
uiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "uiTestJunit4" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazziCompose = { group = "io.github.takahirom.roborazzi", name = "roborazzi-compose", version.ref = "roborazzi" }
roborazziJUnitRule = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
junitPlatformEngine = { group = "org.junit.platform", name = "junit-platform-engine", version.ref = "junitPlatform" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatform" }
assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertjCore" }

detektFormatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
robsRules = { group = "dev.robch.rules", name = "robs-rules", version.ref = "robsRules" }

[bundles]
plugins = [
    "plugin-androidApplication",
    "plugin-androidLibrary",
    "plugin-compose",
    "plugin-composeCompiler",
    "plugin-composeHotReload",
    "plugin-crashlytics",
    "plugin-detektGradle",
    "plugin-firebasePerf",
    "plugin-googlePlayServices",
    "plugin-kotlinGradle",
    "plugin-kotlinParcelize",
    "plugin-kotlinSerialization",
    "plugin-ksp",
    "plugin-metro",
    "plugin-roborazzi",
    "plugin-room",
]
commonMain = [
    "annotation",
    "coil",
    "coilNetwork",
    "datastore",
    "datastoreCoreOkio",
    "datastorePreferences",
    "datastorePreferencesCore",
    "jetbrainsCore",
    "jetbrainsLifecycleRuntimeCompose",
    "jetbrainsLifecycleViewmodel",
    "jetbrainsLifecycleViewmodelCompose",
    "jetbrainsNavigationCompose",
    "jetbrainsSavedState",
    "jetbrainsWindowCore",
    "kermit",
    "kotlinCollectionsImmutable",
    "kotlinDatetime",
    "kotlinSerializationJson",
    "ksoup",
    "ktorClientContentNegotiation",
    "ktorClientCore",
    "ktorClientLogging",
    "ktorSerializationKotlinJson",
    "material3AdaptiveNavigation",
    "material3WindowSizeClassMultiplatform",
    "roomRuntime",
    "slf4jSimple",
    "sqliteBundled",
]
androidMain = [
    "accompanistAdaptive",
    "activityKtx",
    "appcompat",
    "collectionKtx",
    "coreKtx",
    "coreSplashscreen",
    "firebaseAnalytics",
    "firebaseCrashlytics",
    "firebasePerf",
    "fragmentKtx",
    "kotlinCoroutinesAndroid",
    "kspSymbolProcessingApi",
    "ktorClientAndroid",
    "lifecycleProcess",
    "material3",
    "material3Adaptive",
    "material3AdaptiveLayout",
    "material3AdaptiveNavigationSuite",
    "metricsPerformance",
    "paletteKtx",
    "preferenceKtx",
    "roomKtx",
    "roomPaging",
    "roomRuntime",
    "window",
    "workRuntimeKtx",
]
jvmMain = [
    "datastoreCoreOkioJvm",
    "kotlinCoroutinesSwing",
    "ktorClientJvm",
    "ktorCoilJvm",
]
wear = [
    "composeMaterialWear",
    "composeNavigationWear",
    "playServicesWearable",
]
iosMain = [
    "ktorClientDarwin",
]
commonTest = [
    "kotlinCoroutinesTest",
    "kotlinTest",
]
androidUnitTest = [
    "assertjCore",
    "espressoCore",
    "junit",
    "junitExt",
    "junitJupiter",
    "mockk",
    "robolectric",
    "roborazzi",
    "roborazziCompose",
    "roborazziJUnitRule",
    "uiTestJunit4",
]
#lintApi = [
#    "kotlinStdlib",
#    "lintApi",
#    "lintChecks",
#]
#lintTests = [
#    "junit",
#    "lintCli",
#    "lintTests"
#]
